spring:
  kafka:
    bootstrap-servers: ${KSERVERS}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required  username="${KUSER}" password="${KPWD}";
    consumer:
      group-id: ${KGROUP}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      retries: 0
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 5

  redis:
    host: localhost
    port: 6379
    timeout:
      linger.ms: 500


pubsub:
  host: 0.0.0.0
  port: 8888
  ping_timeout: 5000
  pint_interval: 2500
  upgrade_timeout: 10000
  boss_threads: 4
  worker_threads: 4
  use_linux_native_epoll: false

